#!/usr/bin/env bash

set -e

function cleanup_at_exit {
  git checkout heroku
  git branch -D deploy
}

trap cleanup_at_exit EXIT
git checkout -b deploy
git add . -f
git commit --allow-empty -m 'Deploying'
git push --force heroku deploy:heroku